import {
	UtensilsCrossed,
	Coffee,
	Beer,
	Pizza,
	Soup,
	Sandwich,
	Fish,
	IceCream,
	Wine,
	ChefHat,
	Salad,
	Home,
	Scissors,
	Bath,
	Heart,
	Car,
	Plane,
	Bus,
	TrainFront,
	Bike,
	Hotel,
	Building2,
	Moon,
	Tent,
	MapPin,
	Waves,
	Mountain,
	Building,
	Film,
	Music,
	Camera,
	PartyPopper,
	Gift,
	Gamepad2,
	Dumbbell,
	ShoppingBag,
	ShoppingCart,
	Flower2,
	Lightbulb,
	Mic2,
	PawPrint,
	Landmark,
	Briefcase,
	GraduationCap,
	ClipboardCheck,
	Wallet,
	Star,
	BookOpen,
	Users,
	Sun,
	Sparkles,
	type LucideIcon,
} from 'lucide-react';
import type { CategoryIconKey } from './categoryIcons';

export const REACT_ICONS: Record<CategoryIconKey, LucideIcon> = {
	'utensils-crossed': UtensilsCrossed,
	coffee: Coffee,
	beer: Beer,
	pizza: Pizza,
	soup: Soup,
	sandwich: Sandwich,
	fish: Fish,
	'ice-cream': IceCream,
	wine: Wine,
	'chef-hat': ChefHat,
	salad: Salad,
	home: Home,
	scissors: Scissors,
	bath: Bath,
	heart: Heart,
	car: Car,
	plane: Plane,
	bus: Bus,
	'train-front': TrainFront,
	bike: Bike,
	hotel: Hotel,
	'building-2': Building2,
	moon: Moon,
	tent: Tent,
	'map-pin': MapPin,
	waves: Waves,
	mountain: Mountain,
	building: Building,
	film: Film,
	music: Music,
	camera: Camera,
	'party-popper': PartyPopper,
	gift: Gift,
	'gamepad-2': Gamepad2,
	dumbbell: Dumbbell,
	'shopping-bag': ShoppingBag,
	'shopping-cart': ShoppingCart,
	'flower-2': Flower2,
	lightbulb: Lightbulb,
	'mic-2': Mic2,
	'paw-print': PawPrint,
	landmark: Landmark,
	briefcase: Briefcase,
	'graduation-cap': GraduationCap,
	'clipboard-check': ClipboardCheck,
	wallet: Wallet,
	star: Star,
	'book-open': BookOpen,
	users: Users,
	sun: Sun,
	sparkles: Sparkles,
};
